#remote_theme: pages-themes/leap-day@v0.2.0
remote_theme: JulianChia/lowerboundSARSCOV2.github.io

title: "Singaporeâ€™s SARS-CoV-2 Infection Trend In 2020: A Lower Bound Estimate"
description: "By Julian Chia, 1st March 2022"
show_downloads: false
google_analytics:
theme: jekyll-theme-leap-day
email: julianchiayh@gmail.com
url: "https://github.com/JulianChia/lowerboundSARSCOV2.github.io"

